# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'p_client_kaiyo_notification_development(1)(946bf6c7-3254-4f6e-9430-edf88a9692d1)'
        KeyVaultName: 'kaiyo-notification'
        SecretsFilter: '*'
        RunAsPreJob: true
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'kaiyoserver'
        repository: 'test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'