# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'keyvault'
        KeyVaultName: 'kaiyo-notification'
        SecretsFilter: '*'
        RunAsPreJob: true
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'kaiyoserver'
        repository: 'test'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
        arguments: '--build-arg APP_ENV=$(APP-ENV) --build-arg GITHUB_USER=$(GITHUB-USER) --build-arg GITHUB_PASSWORD=$(GITHUB-PASSWORD)'